version: "3.9"
services:
  nginx:
    image: nginx:latest
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - media:/data/media
    ports:
      - 80:80
  django_gunicorn:
    image: django_database:latest
    networks:
      - network
    volumes:
      - static:/home/snsProject/collect_static
      - media:/home/snsProject/media
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
  mysql:
    image: mysql:8.4.5
    restart: always
    networks:
      - network
    volumes:
      - database:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: turing
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
  network:

volumes:
  static:
  media:
  database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true